name: build and publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Get requirements
      run: sudo apt-get install cmake clang libicu-dev uuid-dev libcurl4-openssl-dev zlib1g-dev libkrb5-dev libtinfo5
    - name: Build with dotnet
      run: dotnet publish /p:NativeLib=Shared -r linux-x64 -c release
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
          # Artifact name
        name: linux-build
          # Directory containing files to upload
        path: ./src/bin
